mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eclipseboard?allowMultiQueries=true
    username: yoonho 
    password: 1qaz
    driver-class-name: com.mysql.cj.jdbc.Driver

    
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
      